import { TradeLog, TradingGroup, LeaderboardEntry, UserProfile } from '@/types';

export const initialUserProfile: UserProfile = {
  id: 'usr_filla_999',
  fullName: 'Filla Calon Wong Sugih 9 Naga',
  email: 'filla.ferari@krtrade.com',
  username: 'Filla_Ferari9Naga',
  tradingStyle: 'Scalping',
  isAgreedTamak: true,
  isAgreedFillaRichest: true,
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Filla9Naga',
};

export const initialTrades: TradeLog[] = [
  {
    id: 'trd_1',
    pair: 'XAU/USD',
    type: 'BUY',
    entryPrice: 2410.50,
    exitPrice: 2435.00,
    lotSize: 2.5,
    pnl: 6125.00,
    rrRatio: 3.2,
    strategy: 'SMC Gold Liquidity Grab',
    notes: 'Entry after liquidity sweep at Asia Low + 5m Fair Value Gap confirmation.',
    screenshotUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
    date: '2026-07-28T14:30:00Z',
  },
  {
    id: 'trd_2',
    pair: 'EUR/USD',
    type: 'SELL',
    entryPrice: 1.0890,
    exitPrice: 1.0830,
    lotSize: 5.0,
    pnl: 3000.00,
    rrRatio: 2.5,
    strategy: 'ICT Order Block Breaker',
    notes: 'London session Killzone rejection off daily bearish order block.',
    screenshotUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80',
    date: '2026-07-29T09:15:00Z',
  },
  {
    id: 'trd_3',
    pair: 'BTC/USD',
    type: 'BUY',
    entryPrice: 66500.00,
    exitPrice: 65800.00,
    lotSize: 0.5,
    pnl: -350.00,
    rrRatio: 1.5,
    strategy: 'Breakout Retest',
    notes: 'Fakeout on 15m timeframe. Stopped out cleanly according to risk plan.',
    screenshotUrl: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=800&auto=format&fit=crop&q=80',
    date: '2026-07-30T18:45:00Z',
  },
  {
    id: 'trd_4',
    pair: 'GBP/JPY',
    type: 'BUY',
    entryPrice: 201.20,
    exitPrice: 203.40,
    lotSize: 3.0,
    pnl: 4400.00,
    rrRatio: 4.0,
    strategy: 'Scalping Momentum',
    notes: 'Tokyo session expansion after BOJ news release.',
    screenshotUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
    date: '2026-07-31T06:10:00Z',
  },
  {
    id: 'trd_5',
    pair: 'XAU/USD',
    type: 'SELL',
    entryPrice: 2445.00,
    exitPrice: 2420.00,
    lotSize: 2.0,
    pnl: 5000.00,
    rrRatio: 3.5,
    strategy: 'SMC Gold Liquidity Grab',
    notes: 'New York session NY Open High manipulation into key resistance.',
    screenshotUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
    date: '2026-08-01T08:20:00Z',
  },
];

export const initialGroups: TradingGroup[] = [
  {
    id: 'grp_1',
    name: 'SMC Scalpers 9 Naga',
    code: 'NAGA99',
    description: 'Komunitas eksklusif trader SMC & ICT yang tidak tamak dan konsisten profit.',
    membersCount: 128,
    totalPnl: 485900.00,
    winRate: 82.4,
    isJoined: true,
  },
  {
    id: 'grp_2',
    name: '9 Naga Elite Traders',
    code: 'ELITE9',
    description: 'Komunitas VIP murid kepercayaan Filla untuk mencapai wealth level tertinggi.',
    membersCount: 45,
    totalPnl: 1240500.00,
    winRate: 88.9,
    isJoined: true,
  },
  {
    id: 'grp_3',
    name: 'Gold Hunters ID',
    code: 'XAU24K',
    description: 'Spesialis scalping & swing XAU/USD dengan disiplin RRR 1:3 minimal.',
    membersCount: 312,
    totalPnl: 670200.00,
    winRate: 74.2,
    isJoined: false,
  },
  {
    id: 'grp_4',
    name: 'Swing Kings International',
    code: 'SWINGK',
    description: 'Trader berkelas santai, hold posisi dari Weekly FVG sampai target 1000 pips.',
    membersCount: 89,
    totalPnl: 340100.00,
    winRate: 79.1,
    isJoined: false,
  },
];

export const initialLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    username: 'Filla_Ferari9Naga',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Filla9Naga',
    tradingStyle: 'Scalping',
    monthlyReturn: 48.5,
    winRate: 85.7,
    totalTrades: 42,
    totalPnl: 42800.00,
    isFriend: true,
    communityId: 'grp_1',
  },
  {
    rank: 2,
    username: 'Sultan_Gold_SMC',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SultanGold',
    tradingStyle: 'Scalping',
    monthlyReturn: 39.2,
    winRate: 81.0,
    totalTrades: 58,
    totalPnl: 34500.00,
    isFriend: true,
    communityId: 'grp_1',
  },
  {
    rank: 3,
    username: 'Baron_Swing_Pro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BaronSwing',
    tradingStyle: 'Swing Trade',
    monthlyReturn: 34.8,
    winRate: 78.4,
    totalTrades: 18,
    totalPnl: 29800.00,
    isFriend: false,
    communityId: 'grp_4',
  },
  {
    rank: 4,
    username: 'Intraday_Sniper99',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IntradaySniper',
    tradingStyle: 'Intraday',
    monthlyReturn: 28.4,
    winRate: 76.5,
    totalTrades: 34,
    totalPnl: 22100.00,
    isFriend: true,
    communityId: 'grp_2',
  },
  {
    rank: 5,
    username: 'Raja_Pip_Nusantara',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RajaPip',
    tradingStyle: 'Scalping',
    monthlyReturn: 26.1,
    winRate: 74.0,
    totalTrades: 89,
    totalPnl: 19400.00,
    isFriend: false,
    communityId: 'grp_3',
  },
  {
    rank: 6,
    username: 'Crypto_Whale_Filla',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CryptoWhale',
    tradingStyle: 'Intraday',
    monthlyReturn: 22.9,
    winRate: 72.8,
    totalTrades: 29,
    totalPnl: 16500.00,
    isFriend: false,
    communityId: 'grp_2',
  },
  {
    rank: 7,
    username: 'Naga_Hijau_Profitable',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NagaHijau',
    tradingStyle: 'Swing Trade',
    monthlyReturn: 19.5,
    winRate: 70.2,
    totalTrades: 14,
    totalPnl: 12900.00,
    isFriend: true,
    communityId: 'grp_1',
  },
];
